matrix:
  include:
    - language: python
      python:
        - "3.7"
      services:
        - mongodb
      install:
        - pip install -r app/requirements.txt
        - pip install codecov
      script:
        - coverage run --source=app/ app/run_tests.py
        # just for now
        - coverage report
      after_success:
        -codecov

    - language: node_js
      node_js:
        - "13"
      install:
        - npm install --prefix app/seekr/
      script:
        - npm test --prefix app/seeker/