matrix:
  include:
    - language: python
      python:
        - "3.7"
      services:
        - mongodb
      install:
        - pip install -r requirements.txt
        - pip install codecov
      script:
        - coverage run --source=./ run_tests.py
        # just for now
        - coverage report

    - language: node_js
      node_js:
        - "13"
      install:
        - npm install --prefix seekr/
      script:
        - npm test --prefix seekr/ a -- --coverage