language: python

python:
  - "3.7"
install:
  - pip install -r app/requirements.txt
  - pip install codecov
script:
  - coverage run --source=app/ app/run_tests.py
  # just for now
  - coverage report
after_success:
  -codecov